### ISSUE TITLE
Why didn't you forked ?

### ISSUE THREAD

**Issue by pierrocknroll** [hivokas/laravel-passport-social-grant#3]
You copied this package https://github.com/adaojunior/passport-social-grant
Without mentionning it or better, forking it
I don't think we need 2 packages for this use, and since adaojunior has participated in the discussions in the laravel/passport package, yours is useless.

**Comment by hivokas** [comment]
It's up to you which one you want to use.
This one is covered by tests.

**Comment by 4levels** [comment]
You could have added your tests and make a PR to the original repo instead.  Credit where credit is due!

**Comment by adaojunior** [comment]
Thanks @4levels, @pierrocknroll. Although I don't mind @hivokas having his own version, I'll have to point that what has been done here is simply copying my code and changing the namespace, even the tests were there before [see](https://github.com/adaojunior/passport-social-grant/tree/9a22326842fb4a5a7a346b0dbe535fca0efcf869/tests).

**Comment by pierrocknroll** [comment]
Yes, you could not blame him, since your LICENCE is MIT.
But it's not very "open source community" friendly.
He copied it for the glory of having an article on Medium, without thinking about potential bug fixes on one side but not on the other.
