### ISSUE TITLE
Passport version constraint

### ISSUE THREAD

**Issue by andrewalba** [hivokas/laravel-passport-social-grant#4]
First off, thanks for the great plugin (what a time saver). Requesting a small update to composer file.  Recently updated `laravel/framework` to version 5.7 and with that came an update to `laravel/passport` version 7. 

We are unable to use this repo with the `laravel/passport` major version 7, as the major version will not update past `laravel/passport` 6, but upon testing there doesn't appear to be any compatibility issue with using `laravel/passport` version 7 with current version of your `laravel-passport-social-grant`.

Was able to fork your repo and branched `composer.json` change here. Tested with Facebook and Google providers and had not issues.

https://github.com/albawebstudio/laravel-passport-social-grant/blob/passport-update/composer.json

Thanks again for your time. Cheers!

**Comment by mrdj07** [comment]
Please merge this :)

**Comment by hivokas** [comment]
I've updated the `composer.json`. So now the package is compatible with Passport 7.
Thanks for opening the issue!
