### ISSUE TITLE
issue return value of App\Resolvers\SocialUserResolver::resolveUserByProviderCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable or null, none returned

### ISSUE THREAD

**Issue by iSarahSajjad** [hivokas/laravel-passport-social-grant#5]
I tired your library, do as the procedure but giving a result value of App\Resolvers\SocialUserResolver::resolveUserByProviderCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable or null, none returned

**Comment by hivokas** [comment]
You should return `User` instance or `null` in `resolveUserByProviderCredentials()` method.
